//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ANTLRv3Parser.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace LanguageServer {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ANTLRv3Parser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public interface IANTLRv3ParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.grammarDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGrammarDef([NotNull] ANTLRv3Parser.GrammarDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.grammarDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGrammarDef([NotNull] ANTLRv3Parser.GrammarDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.tokensSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTokensSpec([NotNull] ANTLRv3Parser.TokensSpecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.tokensSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTokensSpec([NotNull] ANTLRv3Parser.TokensSpecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.tokenSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTokenSpec([NotNull] ANTLRv3Parser.TokenSpecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.tokenSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTokenSpec([NotNull] ANTLRv3Parser.TokenSpecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.attrScope"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttrScope([NotNull] ANTLRv3Parser.AttrScopeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.attrScope"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttrScope([NotNull] ANTLRv3Parser.AttrScopeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAction([NotNull] ANTLRv3Parser.ActionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAction([NotNull] ANTLRv3Parser.ActionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.actionScopeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterActionScopeName([NotNull] ANTLRv3Parser.ActionScopeNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.actionScopeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitActionScopeName([NotNull] ANTLRv3Parser.ActionScopeNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.optionsSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOptionsSpec([NotNull] ANTLRv3Parser.OptionsSpecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.optionsSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOptionsSpec([NotNull] ANTLRv3Parser.OptionsSpecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOption([NotNull] ANTLRv3Parser.OptionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOption([NotNull] ANTLRv3Parser.OptionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.optionValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOptionValue([NotNull] ANTLRv3Parser.OptionValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.optionValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOptionValue([NotNull] ANTLRv3Parser.OptionValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.rules"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRules([NotNull] ANTLRv3Parser.RulesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.rules"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRules([NotNull] ANTLRv3Parser.RulesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.rule_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRule_([NotNull] ANTLRv3Parser.Rule_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.rule_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRule_([NotNull] ANTLRv3Parser.Rule_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.ruleAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRuleAction([NotNull] ANTLRv3Parser.RuleActionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.ruleAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRuleAction([NotNull] ANTLRv3Parser.RuleActionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.throwsSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterThrowsSpec([NotNull] ANTLRv3Parser.ThrowsSpecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.throwsSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitThrowsSpec([NotNull] ANTLRv3Parser.ThrowsSpecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.ruleScopeSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRuleScopeSpec([NotNull] ANTLRv3Parser.RuleScopeSpecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.ruleScopeSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRuleScopeSpec([NotNull] ANTLRv3Parser.RuleScopeSpecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] ANTLRv3Parser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] ANTLRv3Parser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.altList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAltList([NotNull] ANTLRv3Parser.AltListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.altList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAltList([NotNull] ANTLRv3Parser.AltListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.alternative"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAlternative([NotNull] ANTLRv3Parser.AlternativeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.alternative"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAlternative([NotNull] ANTLRv3Parser.AlternativeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.exceptionGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExceptionGroup([NotNull] ANTLRv3Parser.ExceptionGroupContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.exceptionGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExceptionGroup([NotNull] ANTLRv3Parser.ExceptionGroupContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.exceptionHandler"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExceptionHandler([NotNull] ANTLRv3Parser.ExceptionHandlerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.exceptionHandler"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExceptionHandler([NotNull] ANTLRv3Parser.ExceptionHandlerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.finallyClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFinallyClause([NotNull] ANTLRv3Parser.FinallyClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.finallyClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFinallyClause([NotNull] ANTLRv3Parser.FinallyClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElement([NotNull] ANTLRv3Parser.ElementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElement([NotNull] ANTLRv3Parser.ElementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.elementNoOptionSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElementNoOptionSpec([NotNull] ANTLRv3Parser.ElementNoOptionSpecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.elementNoOptionSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElementNoOptionSpec([NotNull] ANTLRv3Parser.ElementNoOptionSpecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.actionBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterActionBlock([NotNull] ANTLRv3Parser.ActionBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.actionBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitActionBlock([NotNull] ANTLRv3Parser.ActionBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.argActionBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgActionBlock([NotNull] ANTLRv3Parser.ArgActionBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.argActionBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgActionBlock([NotNull] ANTLRv3Parser.ArgActionBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtom([NotNull] ANTLRv3Parser.AtomContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtom([NotNull] ANTLRv3Parser.AtomContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.notSet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNotSet([NotNull] ANTLRv3Parser.NotSetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.notSet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNotSet([NotNull] ANTLRv3Parser.NotSetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.treeSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTreeSpec([NotNull] ANTLRv3Parser.TreeSpecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.treeSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTreeSpec([NotNull] ANTLRv3Parser.TreeSpecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.ebnf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEbnf([NotNull] ANTLRv3Parser.EbnfContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.ebnf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEbnf([NotNull] ANTLRv3Parser.EbnfContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.range"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRange([NotNull] ANTLRv3Parser.RangeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.range"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRange([NotNull] ANTLRv3Parser.RangeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.terminal_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerminal_([NotNull] ANTLRv3Parser.Terminal_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.terminal_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerminal_([NotNull] ANTLRv3Parser.Terminal_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.elementOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElementOptions([NotNull] ANTLRv3Parser.ElementOptionsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.elementOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElementOptions([NotNull] ANTLRv3Parser.ElementOptionsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.defaultNodeOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefaultNodeOption([NotNull] ANTLRv3Parser.DefaultNodeOptionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.defaultNodeOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefaultNodeOption([NotNull] ANTLRv3Parser.DefaultNodeOptionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.elementOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElementOption([NotNull] ANTLRv3Parser.ElementOptionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.elementOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElementOption([NotNull] ANTLRv3Parser.ElementOptionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.elementOptionId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElementOptionId([NotNull] ANTLRv3Parser.ElementOptionIdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.elementOptionId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElementOptionId([NotNull] ANTLRv3Parser.ElementOptionIdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.notTerminal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNotTerminal([NotNull] ANTLRv3Parser.NotTerminalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.notTerminal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNotTerminal([NotNull] ANTLRv3Parser.NotTerminalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.ebnfSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEbnfSuffix([NotNull] ANTLRv3Parser.EbnfSuffixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.ebnfSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEbnfSuffix([NotNull] ANTLRv3Parser.EbnfSuffixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.rewrite"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRewrite([NotNull] ANTLRv3Parser.RewriteContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.rewrite"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRewrite([NotNull] ANTLRv3Parser.RewriteContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.rewrite_alternative"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRewrite_alternative([NotNull] ANTLRv3Parser.Rewrite_alternativeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.rewrite_alternative"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRewrite_alternative([NotNull] ANTLRv3Parser.Rewrite_alternativeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.rewrite_tree_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRewrite_tree_block([NotNull] ANTLRv3Parser.Rewrite_tree_blockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.rewrite_tree_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRewrite_tree_block([NotNull] ANTLRv3Parser.Rewrite_tree_blockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.rewrite_tree_alternative"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRewrite_tree_alternative([NotNull] ANTLRv3Parser.Rewrite_tree_alternativeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.rewrite_tree_alternative"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRewrite_tree_alternative([NotNull] ANTLRv3Parser.Rewrite_tree_alternativeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.rewrite_tree_element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRewrite_tree_element([NotNull] ANTLRv3Parser.Rewrite_tree_elementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.rewrite_tree_element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRewrite_tree_element([NotNull] ANTLRv3Parser.Rewrite_tree_elementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.rewrite_tree_atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRewrite_tree_atom([NotNull] ANTLRv3Parser.Rewrite_tree_atomContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.rewrite_tree_atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRewrite_tree_atom([NotNull] ANTLRv3Parser.Rewrite_tree_atomContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.rewrite_tree_ebnf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRewrite_tree_ebnf([NotNull] ANTLRv3Parser.Rewrite_tree_ebnfContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.rewrite_tree_ebnf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRewrite_tree_ebnf([NotNull] ANTLRv3Parser.Rewrite_tree_ebnfContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.rewrite_tree"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRewrite_tree([NotNull] ANTLRv3Parser.Rewrite_treeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.rewrite_tree"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRewrite_tree([NotNull] ANTLRv3Parser.Rewrite_treeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.rewrite_template"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRewrite_template([NotNull] ANTLRv3Parser.Rewrite_templateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.rewrite_template"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRewrite_template([NotNull] ANTLRv3Parser.Rewrite_templateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.rewrite_template_ref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRewrite_template_ref([NotNull] ANTLRv3Parser.Rewrite_template_refContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.rewrite_template_ref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRewrite_template_ref([NotNull] ANTLRv3Parser.Rewrite_template_refContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.rewrite_indirect_template_head"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRewrite_indirect_template_head([NotNull] ANTLRv3Parser.Rewrite_indirect_template_headContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.rewrite_indirect_template_head"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRewrite_indirect_template_head([NotNull] ANTLRv3Parser.Rewrite_indirect_template_headContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.rewrite_template_args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRewrite_template_args([NotNull] ANTLRv3Parser.Rewrite_template_argsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.rewrite_template_args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRewrite_template_args([NotNull] ANTLRv3Parser.Rewrite_template_argsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.rewrite_template_arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRewrite_template_arg([NotNull] ANTLRv3Parser.Rewrite_template_argContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.rewrite_template_arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRewrite_template_arg([NotNull] ANTLRv3Parser.Rewrite_template_argContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv3Parser.id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterId([NotNull] ANTLRv3Parser.IdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv3Parser.id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitId([NotNull] ANTLRv3Parser.IdContext context);
}
} // namespace LanguageServer
