//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ANTLRv2Parser.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace LanguageServer {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ANTLRv2Parser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public interface IANTLRv2ParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.grammar_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGrammar_([NotNull] ANTLRv2Parser.Grammar_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.grammar_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGrammar_([NotNull] ANTLRv2Parser.Grammar_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.header_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHeader_([NotNull] ANTLRv2Parser.Header_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.header_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHeader_([NotNull] ANTLRv2Parser.Header_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.classDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassDef([NotNull] ANTLRv2Parser.ClassDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.classDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassDef([NotNull] ANTLRv2Parser.ClassDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.fileOptionsSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFileOptionsSpec([NotNull] ANTLRv2Parser.FileOptionsSpecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.fileOptionsSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFileOptionsSpec([NotNull] ANTLRv2Parser.FileOptionsSpecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.parserOptionsSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParserOptionsSpec([NotNull] ANTLRv2Parser.ParserOptionsSpecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.parserOptionsSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParserOptionsSpec([NotNull] ANTLRv2Parser.ParserOptionsSpecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.treeParserOptionsSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTreeParserOptionsSpec([NotNull] ANTLRv2Parser.TreeParserOptionsSpecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.treeParserOptionsSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTreeParserOptionsSpec([NotNull] ANTLRv2Parser.TreeParserOptionsSpecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.lexerOptionsSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLexerOptionsSpec([NotNull] ANTLRv2Parser.LexerOptionsSpecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.lexerOptionsSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLexerOptionsSpec([NotNull] ANTLRv2Parser.LexerOptionsSpecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.subruleOptionsSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubruleOptionsSpec([NotNull] ANTLRv2Parser.SubruleOptionsSpecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.subruleOptionsSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubruleOptionsSpec([NotNull] ANTLRv2Parser.SubruleOptionsSpecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOption([NotNull] ANTLRv2Parser.OptionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOption([NotNull] ANTLRv2Parser.OptionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.optionValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOptionValue([NotNull] ANTLRv2Parser.OptionValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.optionValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOptionValue([NotNull] ANTLRv2Parser.OptionValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.lexerOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLexerOption([NotNull] ANTLRv2Parser.LexerOptionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.lexerOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLexerOption([NotNull] ANTLRv2Parser.LexerOptionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.lexerOptionValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLexerOptionValue([NotNull] ANTLRv2Parser.LexerOptionValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.lexerOptionValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLexerOptionValue([NotNull] ANTLRv2Parser.LexerOptionValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.charSet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCharSet([NotNull] ANTLRv2Parser.CharSetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.charSet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCharSet([NotNull] ANTLRv2Parser.CharSetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.setBlockElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetBlockElement([NotNull] ANTLRv2Parser.SetBlockElementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.setBlockElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetBlockElement([NotNull] ANTLRv2Parser.SetBlockElementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.tokensSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTokensSpec([NotNull] ANTLRv2Parser.TokensSpecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.tokensSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTokensSpec([NotNull] ANTLRv2Parser.TokensSpecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.tokenEntry"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTokenEntry([NotNull] ANTLRv2Parser.TokenEntryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.tokenEntry"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTokenEntry([NotNull] ANTLRv2Parser.TokenEntryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.tokensSpecOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTokensSpecOptions([NotNull] ANTLRv2Parser.TokensSpecOptionsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.tokensSpecOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTokensSpecOptions([NotNull] ANTLRv2Parser.TokensSpecOptionsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.superClass"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSuperClass([NotNull] ANTLRv2Parser.SuperClassContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.superClass"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSuperClass([NotNull] ANTLRv2Parser.SuperClassContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.parserSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParserSpec([NotNull] ANTLRv2Parser.ParserSpecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.parserSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParserSpec([NotNull] ANTLRv2Parser.ParserSpecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.lexerSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLexerSpec([NotNull] ANTLRv2Parser.LexerSpecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.lexerSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLexerSpec([NotNull] ANTLRv2Parser.LexerSpecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.treeParserSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTreeParserSpec([NotNull] ANTLRv2Parser.TreeParserSpecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.treeParserSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTreeParserSpec([NotNull] ANTLRv2Parser.TreeParserSpecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.rules"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRules([NotNull] ANTLRv2Parser.RulesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.rules"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRules([NotNull] ANTLRv2Parser.RulesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.rule_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRule_([NotNull] ANTLRv2Parser.Rule_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.rule_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRule_([NotNull] ANTLRv2Parser.Rule_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.ruleOptionsSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRuleOptionsSpec([NotNull] ANTLRv2Parser.RuleOptionsSpecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.ruleOptionsSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRuleOptionsSpec([NotNull] ANTLRv2Parser.RuleOptionsSpecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.throwsSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterThrowsSpec([NotNull] ANTLRv2Parser.ThrowsSpecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.throwsSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitThrowsSpec([NotNull] ANTLRv2Parser.ThrowsSpecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] ANTLRv2Parser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] ANTLRv2Parser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.alternative"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAlternative([NotNull] ANTLRv2Parser.AlternativeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.alternative"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAlternative([NotNull] ANTLRv2Parser.AlternativeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.exceptionGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExceptionGroup([NotNull] ANTLRv2Parser.ExceptionGroupContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.exceptionGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExceptionGroup([NotNull] ANTLRv2Parser.ExceptionGroupContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.exceptionSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExceptionSpec([NotNull] ANTLRv2Parser.ExceptionSpecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.exceptionSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExceptionSpec([NotNull] ANTLRv2Parser.ExceptionSpecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.exceptionSpecNoLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExceptionSpecNoLabel([NotNull] ANTLRv2Parser.ExceptionSpecNoLabelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.exceptionSpecNoLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExceptionSpecNoLabel([NotNull] ANTLRv2Parser.ExceptionSpecNoLabelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.exceptionHandler"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExceptionHandler([NotNull] ANTLRv2Parser.ExceptionHandlerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.exceptionHandler"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExceptionHandler([NotNull] ANTLRv2Parser.ExceptionHandlerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElement([NotNull] ANTLRv2Parser.ElementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElement([NotNull] ANTLRv2Parser.ElementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.elementOptionSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElementOptionSpec([NotNull] ANTLRv2Parser.ElementOptionSpecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.elementOptionSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElementOptionSpec([NotNull] ANTLRv2Parser.ElementOptionSpecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.elementNoOptionSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElementNoOptionSpec([NotNull] ANTLRv2Parser.ElementNoOptionSpecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.elementNoOptionSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElementNoOptionSpec([NotNull] ANTLRv2Parser.ElementNoOptionSpecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.rule_ref_or_keyword_as"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRule_ref_or_keyword_as([NotNull] ANTLRv2Parser.Rule_ref_or_keyword_asContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.rule_ref_or_keyword_as"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRule_ref_or_keyword_as([NotNull] ANTLRv2Parser.Rule_ref_or_keyword_asContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.tree_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTree_([NotNull] ANTLRv2Parser.Tree_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.tree_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTree_([NotNull] ANTLRv2Parser.Tree_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.rootNode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRootNode([NotNull] ANTLRv2Parser.RootNodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.rootNode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRootNode([NotNull] ANTLRv2Parser.RootNodeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.ebnf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEbnf([NotNull] ANTLRv2Parser.EbnfContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.ebnf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEbnf([NotNull] ANTLRv2Parser.EbnfContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.ast_type_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAst_type_spec([NotNull] ANTLRv2Parser.Ast_type_specContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.ast_type_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAst_type_spec([NotNull] ANTLRv2Parser.Ast_type_specContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.range"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRange([NotNull] ANTLRv2Parser.RangeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.range"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRange([NotNull] ANTLRv2Parser.RangeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.terminal_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerminal_([NotNull] ANTLRv2Parser.Terminal_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.terminal_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerminal_([NotNull] ANTLRv2Parser.Terminal_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.notTerminal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNotTerminal([NotNull] ANTLRv2Parser.NotTerminalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.notTerminal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNotTerminal([NotNull] ANTLRv2Parser.NotTerminalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.qualifiedID"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQualifiedID([NotNull] ANTLRv2Parser.QualifiedIDContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.qualifiedID"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQualifiedID([NotNull] ANTLRv2Parser.QualifiedIDContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterId([NotNull] ANTLRv2Parser.IdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitId([NotNull] ANTLRv2Parser.IdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAction([NotNull] ANTLRv2Parser.ActionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAction([NotNull] ANTLRv2Parser.ActionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.actionScopeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterActionScopeName([NotNull] ANTLRv2Parser.ActionScopeNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.actionScopeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitActionScopeName([NotNull] ANTLRv2Parser.ActionScopeNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.ruleAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRuleAction([NotNull] ANTLRv2Parser.RuleActionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.ruleAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRuleAction([NotNull] ANTLRv2Parser.RuleActionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.altList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAltList([NotNull] ANTLRv2Parser.AltListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.altList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAltList([NotNull] ANTLRv2Parser.AltListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.actionBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterActionBlock([NotNull] ANTLRv2Parser.ActionBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.actionBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitActionBlock([NotNull] ANTLRv2Parser.ActionBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ANTLRv2Parser.argActionBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgActionBlock([NotNull] ANTLRv2Parser.ArgActionBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ANTLRv2Parser.argActionBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgActionBlock([NotNull] ANTLRv2Parser.ArgActionBlockContext context);
}
} // namespace LanguageServer
