//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Iso14977Parser.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace LanguageServer {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IIso14977ParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class Iso14977ParserBaseListener : IIso14977ParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.letter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLetter([NotNull] Iso14977Parser.LetterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.letter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLetter([NotNull] Iso14977Parser.LetterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.decimal_digit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDecimal_digit([NotNull] Iso14977Parser.Decimal_digitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.decimal_digit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDecimal_digit([NotNull] Iso14977Parser.Decimal_digitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.concatenate_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConcatenate_symbol([NotNull] Iso14977Parser.Concatenate_symbolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.concatenate_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConcatenate_symbol([NotNull] Iso14977Parser.Concatenate_symbolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.defining_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefining_symbol([NotNull] Iso14977Parser.Defining_symbolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.defining_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefining_symbol([NotNull] Iso14977Parser.Defining_symbolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.definition_separator_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefinition_separator_symbol([NotNull] Iso14977Parser.Definition_separator_symbolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.definition_separator_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefinition_separator_symbol([NotNull] Iso14977Parser.Definition_separator_symbolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.end_comment_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnd_comment_symbol([NotNull] Iso14977Parser.End_comment_symbolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.end_comment_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnd_comment_symbol([NotNull] Iso14977Parser.End_comment_symbolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.end_group_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnd_group_symbol([NotNull] Iso14977Parser.End_group_symbolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.end_group_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnd_group_symbol([NotNull] Iso14977Parser.End_group_symbolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.end_option_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnd_option_symbol([NotNull] Iso14977Parser.End_option_symbolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.end_option_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnd_option_symbol([NotNull] Iso14977Parser.End_option_symbolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.end_repeat_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnd_repeat_symbol([NotNull] Iso14977Parser.End_repeat_symbolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.end_repeat_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnd_repeat_symbol([NotNull] Iso14977Parser.End_repeat_symbolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.except_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExcept_symbol([NotNull] Iso14977Parser.Except_symbolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.except_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExcept_symbol([NotNull] Iso14977Parser.Except_symbolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.first_quote_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFirst_quote_symbol([NotNull] Iso14977Parser.First_quote_symbolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.first_quote_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFirst_quote_symbol([NotNull] Iso14977Parser.First_quote_symbolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.repetition_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRepetition_symbol([NotNull] Iso14977Parser.Repetition_symbolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.repetition_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRepetition_symbol([NotNull] Iso14977Parser.Repetition_symbolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.second_quote_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSecond_quote_symbol([NotNull] Iso14977Parser.Second_quote_symbolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.second_quote_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSecond_quote_symbol([NotNull] Iso14977Parser.Second_quote_symbolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.special_sequence_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpecial_sequence_symbol([NotNull] Iso14977Parser.Special_sequence_symbolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.special_sequence_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpecial_sequence_symbol([NotNull] Iso14977Parser.Special_sequence_symbolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.start_comment_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStart_comment_symbol([NotNull] Iso14977Parser.Start_comment_symbolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.start_comment_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStart_comment_symbol([NotNull] Iso14977Parser.Start_comment_symbolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.start_group_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStart_group_symbol([NotNull] Iso14977Parser.Start_group_symbolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.start_group_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStart_group_symbol([NotNull] Iso14977Parser.Start_group_symbolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.start_option_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStart_option_symbol([NotNull] Iso14977Parser.Start_option_symbolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.start_option_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStart_option_symbol([NotNull] Iso14977Parser.Start_option_symbolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.start_repeat_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStart_repeat_symbol([NotNull] Iso14977Parser.Start_repeat_symbolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.start_repeat_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStart_repeat_symbol([NotNull] Iso14977Parser.Start_repeat_symbolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.terminator_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerminator_symbol([NotNull] Iso14977Parser.Terminator_symbolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.terminator_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerminator_symbol([NotNull] Iso14977Parser.Terminator_symbolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.other_character"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOther_character([NotNull] Iso14977Parser.Other_characterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.other_character"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOther_character([NotNull] Iso14977Parser.Other_characterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.space_character"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpace_character([NotNull] Iso14977Parser.Space_characterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.space_character"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpace_character([NotNull] Iso14977Parser.Space_characterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.horizontal_tabulation_character"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHorizontal_tabulation_character([NotNull] Iso14977Parser.Horizontal_tabulation_characterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.horizontal_tabulation_character"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHorizontal_tabulation_character([NotNull] Iso14977Parser.Horizontal_tabulation_characterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.new_line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNew_line([NotNull] Iso14977Parser.New_lineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.new_line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNew_line([NotNull] Iso14977Parser.New_lineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.vertical_tabulation_character"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVertical_tabulation_character([NotNull] Iso14977Parser.Vertical_tabulation_characterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.vertical_tabulation_character"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVertical_tabulation_character([NotNull] Iso14977Parser.Vertical_tabulation_characterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.form_feed"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForm_feed([NotNull] Iso14977Parser.Form_feedContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.form_feed"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForm_feed([NotNull] Iso14977Parser.Form_feedContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.terminal_character"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerminal_character([NotNull] Iso14977Parser.Terminal_characterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.terminal_character"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerminal_character([NotNull] Iso14977Parser.Terminal_characterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.gap_free_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGap_free_symbol([NotNull] Iso14977Parser.Gap_free_symbolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.gap_free_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGap_free_symbol([NotNull] Iso14977Parser.Gap_free_symbolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.terminal_string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerminal_string([NotNull] Iso14977Parser.Terminal_stringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.terminal_string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerminal_string([NotNull] Iso14977Parser.Terminal_stringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.first_terminal_character"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFirst_terminal_character([NotNull] Iso14977Parser.First_terminal_characterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.first_terminal_character"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFirst_terminal_character([NotNull] Iso14977Parser.First_terminal_characterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.second_terminal_character"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSecond_terminal_character([NotNull] Iso14977Parser.Second_terminal_characterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.second_terminal_character"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSecond_terminal_character([NotNull] Iso14977Parser.Second_terminal_characterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.gap_separator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGap_separator([NotNull] Iso14977Parser.Gap_separatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.gap_separator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGap_separator([NotNull] Iso14977Parser.Gap_separatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.syntax1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSyntax1([NotNull] Iso14977Parser.Syntax1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.syntax1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSyntax1([NotNull] Iso14977Parser.Syntax1Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.commentless_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommentless_symbol([NotNull] Iso14977Parser.Commentless_symbolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.commentless_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommentless_symbol([NotNull] Iso14977Parser.Commentless_symbolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.integer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInteger([NotNull] Iso14977Parser.IntegerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.integer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInteger([NotNull] Iso14977Parser.IntegerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.meta_identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMeta_identifier([NotNull] Iso14977Parser.Meta_identifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.meta_identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMeta_identifier([NotNull] Iso14977Parser.Meta_identifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.meta_identifier_character"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMeta_identifier_character([NotNull] Iso14977Parser.Meta_identifier_characterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.meta_identifier_character"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMeta_identifier_character([NotNull] Iso14977Parser.Meta_identifier_characterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.special_sequence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpecial_sequence([NotNull] Iso14977Parser.Special_sequenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.special_sequence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpecial_sequence([NotNull] Iso14977Parser.Special_sequenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.special_sequence_character"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpecial_sequence_character([NotNull] Iso14977Parser.Special_sequence_characterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.special_sequence_character"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpecial_sequence_character([NotNull] Iso14977Parser.Special_sequence_characterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.comment_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComment_symbol([NotNull] Iso14977Parser.Comment_symbolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.comment_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComment_symbol([NotNull] Iso14977Parser.Comment_symbolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.bracketed_textual_comment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBracketed_textual_comment([NotNull] Iso14977Parser.Bracketed_textual_commentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.bracketed_textual_comment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBracketed_textual_comment([NotNull] Iso14977Parser.Bracketed_textual_commentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.syntax2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSyntax2([NotNull] Iso14977Parser.Syntax2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.syntax2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSyntax2([NotNull] Iso14977Parser.Syntax2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.syntax3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSyntax3([NotNull] Iso14977Parser.Syntax3Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.syntax3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSyntax3([NotNull] Iso14977Parser.Syntax3Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.syntax_rule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSyntax_rule([NotNull] Iso14977Parser.Syntax_ruleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.syntax_rule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSyntax_rule([NotNull] Iso14977Parser.Syntax_ruleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.definitions_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefinitions_list([NotNull] Iso14977Parser.Definitions_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.definitions_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefinitions_list([NotNull] Iso14977Parser.Definitions_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.single_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSingle_definition([NotNull] Iso14977Parser.Single_definitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.single_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSingle_definition([NotNull] Iso14977Parser.Single_definitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.syntactic_term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSyntactic_term([NotNull] Iso14977Parser.Syntactic_termContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.syntactic_term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSyntactic_term([NotNull] Iso14977Parser.Syntactic_termContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.syntactic_exception"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSyntactic_exception([NotNull] Iso14977Parser.Syntactic_exceptionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.syntactic_exception"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSyntactic_exception([NotNull] Iso14977Parser.Syntactic_exceptionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.syntactic_factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSyntactic_factor([NotNull] Iso14977Parser.Syntactic_factorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.syntactic_factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSyntactic_factor([NotNull] Iso14977Parser.Syntactic_factorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.syntactic_primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSyntactic_primary([NotNull] Iso14977Parser.Syntactic_primaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.syntactic_primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSyntactic_primary([NotNull] Iso14977Parser.Syntactic_primaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.optional_sequence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOptional_sequence([NotNull] Iso14977Parser.Optional_sequenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.optional_sequence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOptional_sequence([NotNull] Iso14977Parser.Optional_sequenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.repeated_sequence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRepeated_sequence([NotNull] Iso14977Parser.Repeated_sequenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.repeated_sequence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRepeated_sequence([NotNull] Iso14977Parser.Repeated_sequenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.grouped_sequence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGrouped_sequence([NotNull] Iso14977Parser.Grouped_sequenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.grouped_sequence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGrouped_sequence([NotNull] Iso14977Parser.Grouped_sequenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Iso14977Parser.empty_sequence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEmpty_sequence([NotNull] Iso14977Parser.Empty_sequenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Iso14977Parser.empty_sequence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEmpty_sequence([NotNull] Iso14977Parser.Empty_sequenceContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace LanguageServer
