dotnet tool install -g trfold
dotnet tool install -g trfoldlit
dotnet tool install -g trgen
dotnet tool install -g trgroup
dotnet tool install -g trjson
dotnet tool install -g trkleene
dotnet tool install -g trparse
dotnet tool install -g trprint
dotnet tool install -g trst
dotnet tool install -g trstrip
dotnet tool install -g trtext
dotnet tool install -g trtokens
dotnet tool install -g trtree
dotnet tool install -g trunfold
dotnet tool install -g trungroup
dotnet tool install -g trxgrep
dotnet tool install -g trxml
dotnet tool install -g trxml2
