dotnet tool uninstall -g trfold
dotnet tool uninstall -g trgen
dotnet tool uninstall -g trgroup
dotnet tool uninstall -g trjson
dotnet tool uninstall -g trkleene
dotnet tool uninstall -g trparse
dotnet tool uninstall -g trprint
dotnet tool uninstall -g trst
dotnet tool uninstall -g trstrip
dotnet tool uninstall -g trtext
dotnet tool uninstall -g trtokens
dotnet tool uninstall -g trtree
dotnet tool uninstall -g trunfold
dotnet tool uninstall -g trungroup
dotnet tool uninstall -g trxgrep
dotnet tool uninstall -g trxml
