//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ixmlParser.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ixmlParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IixmlParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ixmlParser.ixml"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIxml([NotNull] ixmlParser.IxmlContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ixmlParser.ixml"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIxml([NotNull] ixmlParser.IxmlContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ixmlParser.prolog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProlog([NotNull] ixmlParser.PrologContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ixmlParser.prolog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProlog([NotNull] ixmlParser.PrologContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ixmlParser.version"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVersion([NotNull] ixmlParser.VersionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ixmlParser.version"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVersion([NotNull] ixmlParser.VersionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ixmlParser.rule_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRule_([NotNull] ixmlParser.Rule_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ixmlParser.rule_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRule_([NotNull] ixmlParser.Rule_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ixmlParser.mark"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMark([NotNull] ixmlParser.MarkContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ixmlParser.mark"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMark([NotNull] ixmlParser.MarkContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ixmlParser.alts"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAlts([NotNull] ixmlParser.AltsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ixmlParser.alts"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAlts([NotNull] ixmlParser.AltsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ixmlParser.alt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAlt([NotNull] ixmlParser.AltContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ixmlParser.alt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAlt([NotNull] ixmlParser.AltContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ixmlParser.term_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerm_([NotNull] ixmlParser.Term_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ixmlParser.term_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerm_([NotNull] ixmlParser.Term_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ixmlParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactor([NotNull] ixmlParser.FactorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ixmlParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactor([NotNull] ixmlParser.FactorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ixmlParser.repeat0"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRepeat0([NotNull] ixmlParser.Repeat0Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ixmlParser.repeat0"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRepeat0([NotNull] ixmlParser.Repeat0Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ixmlParser.repeat1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRepeat1([NotNull] ixmlParser.Repeat1Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ixmlParser.repeat1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRepeat1([NotNull] ixmlParser.Repeat1Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ixmlParser.option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOption([NotNull] ixmlParser.OptionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ixmlParser.option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOption([NotNull] ixmlParser.OptionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ixmlParser.sep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSep([NotNull] ixmlParser.SepContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ixmlParser.sep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSep([NotNull] ixmlParser.SepContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ixmlParser.nonterminal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNonterminal([NotNull] ixmlParser.NonterminalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ixmlParser.nonterminal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNonterminal([NotNull] ixmlParser.NonterminalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ixmlParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterName([NotNull] ixmlParser.NameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ixmlParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitName([NotNull] ixmlParser.NameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ixmlParser.terminal_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerminal_([NotNull] ixmlParser.Terminal_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ixmlParser.terminal_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerminal_([NotNull] ixmlParser.Terminal_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ixmlParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral([NotNull] ixmlParser.LiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ixmlParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral([NotNull] ixmlParser.LiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ixmlParser.quoted"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuoted([NotNull] ixmlParser.QuotedContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ixmlParser.quoted"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuoted([NotNull] ixmlParser.QuotedContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ixmlParser.tmark"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTmark([NotNull] ixmlParser.TmarkContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ixmlParser.tmark"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTmark([NotNull] ixmlParser.TmarkContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ixmlParser.string_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString_([NotNull] ixmlParser.String_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ixmlParser.string_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString_([NotNull] ixmlParser.String_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ixmlParser.dchar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDchar([NotNull] ixmlParser.DcharContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ixmlParser.dchar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDchar([NotNull] ixmlParser.DcharContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ixmlParser.schar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSchar([NotNull] ixmlParser.ScharContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ixmlParser.schar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSchar([NotNull] ixmlParser.ScharContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ixmlParser.encoded"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEncoded([NotNull] ixmlParser.EncodedContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ixmlParser.encoded"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEncoded([NotNull] ixmlParser.EncodedContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ixmlParser.hex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHex([NotNull] ixmlParser.HexContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ixmlParser.hex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHex([NotNull] ixmlParser.HexContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ixmlParser.charset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCharset([NotNull] ixmlParser.CharsetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ixmlParser.charset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCharset([NotNull] ixmlParser.CharsetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ixmlParser.inclusion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInclusion([NotNull] ixmlParser.InclusionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ixmlParser.inclusion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInclusion([NotNull] ixmlParser.InclusionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ixmlParser.exclusion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExclusion([NotNull] ixmlParser.ExclusionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ixmlParser.exclusion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExclusion([NotNull] ixmlParser.ExclusionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ixmlParser.set_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSet_([NotNull] ixmlParser.Set_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ixmlParser.set_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSet_([NotNull] ixmlParser.Set_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ixmlParser.member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMember([NotNull] ixmlParser.MemberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ixmlParser.member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMember([NotNull] ixmlParser.MemberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ixmlParser.range_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRange_([NotNull] ixmlParser.Range_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ixmlParser.range_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRange_([NotNull] ixmlParser.Range_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ixmlParser.from_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFrom_([NotNull] ixmlParser.From_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ixmlParser.from_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFrom_([NotNull] ixmlParser.From_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ixmlParser.to_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTo_([NotNull] ixmlParser.To_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ixmlParser.to_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTo_([NotNull] ixmlParser.To_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ixmlParser.character"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCharacter([NotNull] ixmlParser.CharacterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ixmlParser.character"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCharacter([NotNull] ixmlParser.CharacterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ixmlParser.class_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClass_([NotNull] ixmlParser.Class_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ixmlParser.class_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClass_([NotNull] ixmlParser.Class_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ixmlParser.code"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCode([NotNull] ixmlParser.CodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ixmlParser.code"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCode([NotNull] ixmlParser.CodeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ixmlParser.insertion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInsertion([NotNull] ixmlParser.InsertionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ixmlParser.insertion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInsertion([NotNull] ixmlParser.InsertionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ixmlParser.s"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterS([NotNull] ixmlParser.SContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ixmlParser.s"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitS([NotNull] ixmlParser.SContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ixmlParser.rs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRs([NotNull] ixmlParser.RsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ixmlParser.rs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRs([NotNull] ixmlParser.RsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ixmlParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComment([NotNull] ixmlParser.CommentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ixmlParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComment([NotNull] ixmlParser.CommentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ixmlParser.cchar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCchar([NotNull] ixmlParser.CcharContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ixmlParser.cchar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCchar([NotNull] ixmlParser.CcharContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ixmlParser.whitespace_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhitespace_([NotNull] ixmlParser.Whitespace_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ixmlParser.whitespace_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhitespace_([NotNull] ixmlParser.Whitespace_Context context);
}
