# Generated code from Antlr4BuildTasks.dotnet-antlr v 0.7.0
GENERATED = ArithmeticLexer.cs ArithmeticParser.cs 
default:
	dotnet restore
	dotnet build
run:
	trwdog dotnet run $(RUNARGS)
clean:
	dotnet clean
	rm -rf bin obj
test:
	bash test.sh
