child::after, child::allowing, child::ancestor, child::ancestor-or-self, child::and,
child::array, child::as, child::ascending, child::at, child::attribute, child::base-uri,
child::before, child::boundary-space, child::by, child::case, child::cast, child::castable,
child::catch, child::child, child::collation, child::comment, child::construction,
child::context, child::copy-namespaces, child::count, child::decimal-format,
child::decimal-separator, child::declare, child::default, child::descendant,
child::descendant-or-self, child::descending, child::digit, child::div, child::document-node,
child::document, child::element, child::else, child::empty-sequence, child::empty,
child::encoding, child::end, child::enum, child::eq, child::every, child::except,
child::exponent-separator, child::external, child::finally, child::first, child::fn,
child::following, child::following-or-self, child::following-sibling,
child::following-sibling-or-self, child::follows, child::follows-or-is, child::for,
child::function, child::ge, child::gnode, child::greatest, child::group,
child::grouping-separator, child::gt, child::idiv, child::if, child::import, child::in,
child::infinity, child::inherit, child::instance, child::intersect, child::is, child::is-not,
child::item, child::jnode, child::key, child::last, child::lax, child::le, child::least,
child::let, child::lt, child::map, child::member, child::minus-sign, child::mod,
child::module, child::NaN, child::namespace, child::namespace-node, child::ne, child::next,
child::no-inherit, child::no-preserve, child::node, child::of, child::only, child::option,
child::or, child::order, child::ordered, child::ordering, child::otherwise, child::parent,
child::pattern-separator, child::percent, child::per-mille, child::precedes,
child::precedes-or-is, child::preceding, child::preceding-or-self, child::preceding-sibling,
child::preceding-sibling-or-self, child::preserve, child::previous,
child::processing-instruction, child::record, child::return, child::satisfies, child::schema,
child::schema-attribute, child::schema-element, child::self, child::sliding, child::some,
child::stable, child::start, child::strict, child::strip, child::switch, child::text,
child::then, child::to, child::trace, child::treat, child::try, child::tumbling, child::type,
child::typeswitch, child::union, child::unordered, child::validate, child::value,
child::variable, child::version, child::when, child::where, child::while, child::window,
child::xquery, child::zero-digit
