//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Javacc.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="JavaccParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IJavaccListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.runsignedshift"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRunsignedshift([NotNull] JavaccParser.RunsignedshiftContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.runsignedshift"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRunsignedshift([NotNull] JavaccParser.RunsignedshiftContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.rsignedshift"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRsignedshift([NotNull] JavaccParser.RsignedshiftContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.rsignedshift"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRsignedshift([NotNull] JavaccParser.RsignedshiftContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.javacc_input"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJavacc_input([NotNull] JavaccParser.Javacc_inputContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.javacc_input"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJavacc_input([NotNull] JavaccParser.Javacc_inputContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.javacc_options"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJavacc_options([NotNull] JavaccParser.Javacc_optionsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.javacc_options"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJavacc_options([NotNull] JavaccParser.Javacc_optionsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.option_binding"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOption_binding([NotNull] JavaccParser.Option_bindingContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.option_binding"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOption_binding([NotNull] JavaccParser.Option_bindingContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.stringList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringList([NotNull] JavaccParser.StringListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.stringList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringList([NotNull] JavaccParser.StringListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.production"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProduction([NotNull] JavaccParser.ProductionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.production"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProduction([NotNull] JavaccParser.ProductionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.javacode_production"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJavacode_production([NotNull] JavaccParser.Javacode_productionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.javacode_production"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJavacode_production([NotNull] JavaccParser.Javacode_productionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.cppcode_production"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCppcode_production([NotNull] JavaccParser.Cppcode_productionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.cppcode_production"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCppcode_production([NotNull] JavaccParser.Cppcode_productionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.bnf_production"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBnf_production([NotNull] JavaccParser.Bnf_productionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.bnf_production"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBnf_production([NotNull] JavaccParser.Bnf_productionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.accessModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAccessModifier([NotNull] JavaccParser.AccessModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.accessModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAccessModifier([NotNull] JavaccParser.AccessModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.regular_expr_production"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRegular_expr_production([NotNull] JavaccParser.Regular_expr_productionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.regular_expr_production"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRegular_expr_production([NotNull] JavaccParser.Regular_expr_productionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.token_manager_decls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterToken_manager_decls([NotNull] JavaccParser.Token_manager_declsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.token_manager_decls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitToken_manager_decls([NotNull] JavaccParser.Token_manager_declsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.regexpr_kind"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRegexpr_kind([NotNull] JavaccParser.Regexpr_kindContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.regexpr_kind"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRegexpr_kind([NotNull] JavaccParser.Regexpr_kindContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.regexpr_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRegexpr_spec([NotNull] JavaccParser.Regexpr_specContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.regexpr_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRegexpr_spec([NotNull] JavaccParser.Regexpr_specContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.expansion_choices"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpansion_choices([NotNull] JavaccParser.Expansion_choicesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.expansion_choices"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpansion_choices([NotNull] JavaccParser.Expansion_choicesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.expansion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpansion([NotNull] JavaccParser.ExpansionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.expansion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpansion([NotNull] JavaccParser.ExpansionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.local_lookahead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocal_lookahead([NotNull] JavaccParser.Local_lookaheadContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.local_lookahead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocal_lookahead([NotNull] JavaccParser.Local_lookaheadContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.expansion_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpansion_unit([NotNull] JavaccParser.Expansion_unitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.expansion_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpansion_unit([NotNull] JavaccParser.Expansion_unitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.regular_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRegular_expression([NotNull] JavaccParser.Regular_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.regular_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRegular_expression([NotNull] JavaccParser.Regular_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.complex_regular_expression_choices"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComplex_regular_expression_choices([NotNull] JavaccParser.Complex_regular_expression_choicesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.complex_regular_expression_choices"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComplex_regular_expression_choices([NotNull] JavaccParser.Complex_regular_expression_choicesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.complex_regular_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComplex_regular_expression([NotNull] JavaccParser.Complex_regular_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.complex_regular_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComplex_regular_expression([NotNull] JavaccParser.Complex_regular_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.complex_regular_expression_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComplex_regular_expression_unit([NotNull] JavaccParser.Complex_regular_expression_unitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.complex_regular_expression_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComplex_regular_expression_unit([NotNull] JavaccParser.Complex_regular_expression_unitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.character_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCharacter_list([NotNull] JavaccParser.Character_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.character_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCharacter_list([NotNull] JavaccParser.Character_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.character_descriptor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCharacter_descriptor([NotNull] JavaccParser.Character_descriptorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.character_descriptor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCharacter_descriptor([NotNull] JavaccParser.Character_descriptorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier([NotNull] JavaccParser.IdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier([NotNull] JavaccParser.IdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.node_descriptor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNode_descriptor([NotNull] JavaccParser.Node_descriptorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.node_descriptor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNode_descriptor([NotNull] JavaccParser.Node_descriptorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.node_descriptor_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNode_descriptor_expression([NotNull] JavaccParser.Node_descriptor_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.node_descriptor_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNode_descriptor_expression([NotNull] JavaccParser.Node_descriptor_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.javaIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJavaIdentifier([NotNull] JavaccParser.JavaIdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.javaIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJavaIdentifier([NotNull] JavaccParser.JavaIdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.compilationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompilationUnit([NotNull] JavaccParser.CompilationUnitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.compilationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompilationUnit([NotNull] JavaccParser.CompilationUnitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.packageDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPackageDeclaration([NotNull] JavaccParser.PackageDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.packageDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPackageDeclaration([NotNull] JavaccParser.PackageDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.importDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImportDeclaration([NotNull] JavaccParser.ImportDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.importDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImportDeclaration([NotNull] JavaccParser.ImportDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.modifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModifiers([NotNull] JavaccParser.ModifiersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.modifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModifiers([NotNull] JavaccParser.ModifiersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.typeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeDeclaration([NotNull] JavaccParser.TypeDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.typeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeDeclaration([NotNull] JavaccParser.TypeDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.classOrInterfaceDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassOrInterfaceDeclaration([NotNull] JavaccParser.ClassOrInterfaceDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.classOrInterfaceDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassOrInterfaceDeclaration([NotNull] JavaccParser.ClassOrInterfaceDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.extendsList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExtendsList([NotNull] JavaccParser.ExtendsListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.extendsList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExtendsList([NotNull] JavaccParser.ExtendsListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.implementsList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImplementsList([NotNull] JavaccParser.ImplementsListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.implementsList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImplementsList([NotNull] JavaccParser.ImplementsListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.enumDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumDeclaration([NotNull] JavaccParser.EnumDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.enumDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumDeclaration([NotNull] JavaccParser.EnumDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.enumBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumBody([NotNull] JavaccParser.EnumBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.enumBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumBody([NotNull] JavaccParser.EnumBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.enumConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumConstant([NotNull] JavaccParser.EnumConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.enumConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumConstant([NotNull] JavaccParser.EnumConstantContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.typeParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeParameters([NotNull] JavaccParser.TypeParametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.typeParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeParameters([NotNull] JavaccParser.TypeParametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.typeParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeParameter([NotNull] JavaccParser.TypeParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.typeParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeParameter([NotNull] JavaccParser.TypeParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.typeBound"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeBound([NotNull] JavaccParser.TypeBoundContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.typeBound"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeBound([NotNull] JavaccParser.TypeBoundContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.classOrInterfaceBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassOrInterfaceBody([NotNull] JavaccParser.ClassOrInterfaceBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.classOrInterfaceBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassOrInterfaceBody([NotNull] JavaccParser.ClassOrInterfaceBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.classOrInterfaceBodyDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassOrInterfaceBodyDeclaration([NotNull] JavaccParser.ClassOrInterfaceBodyDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.classOrInterfaceBodyDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassOrInterfaceBodyDeclaration([NotNull] JavaccParser.ClassOrInterfaceBodyDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.fieldDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldDeclaration([NotNull] JavaccParser.FieldDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.fieldDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldDeclaration([NotNull] JavaccParser.FieldDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.variableDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDeclarator([NotNull] JavaccParser.VariableDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.variableDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDeclarator([NotNull] JavaccParser.VariableDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.variableDeclaratorId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDeclaratorId([NotNull] JavaccParser.VariableDeclaratorIdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.variableDeclaratorId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDeclaratorId([NotNull] JavaccParser.VariableDeclaratorIdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.variableInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableInitializer([NotNull] JavaccParser.VariableInitializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.variableInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableInitializer([NotNull] JavaccParser.VariableInitializerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.arrayInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayInitializer([NotNull] JavaccParser.ArrayInitializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.arrayInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayInitializer([NotNull] JavaccParser.ArrayInitializerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.methodDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodDeclaration([NotNull] JavaccParser.MethodDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.methodDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodDeclaration([NotNull] JavaccParser.MethodDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.methodDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodDeclarator([NotNull] JavaccParser.MethodDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.methodDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodDeclarator([NotNull] JavaccParser.MethodDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.formalParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormalParameters([NotNull] JavaccParser.FormalParametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.formalParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormalParameters([NotNull] JavaccParser.FormalParametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.formalParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormalParameter([NotNull] JavaccParser.FormalParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.formalParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormalParameter([NotNull] JavaccParser.FormalParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.constructorDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstructorDeclaration([NotNull] JavaccParser.ConstructorDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.constructorDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstructorDeclaration([NotNull] JavaccParser.ConstructorDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.explicitConstructorInvocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExplicitConstructorInvocation([NotNull] JavaccParser.ExplicitConstructorInvocationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.explicitConstructorInvocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExplicitConstructorInvocation([NotNull] JavaccParser.ExplicitConstructorInvocationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitializer([NotNull] JavaccParser.InitializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitializer([NotNull] JavaccParser.InitializerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] JavaccParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] JavaccParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.referenceType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReferenceType([NotNull] JavaccParser.ReferenceTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.referenceType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReferenceType([NotNull] JavaccParser.ReferenceTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.template"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTemplate([NotNull] JavaccParser.TemplateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.template"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTemplate([NotNull] JavaccParser.TemplateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.templateBase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTemplateBase([NotNull] JavaccParser.TemplateBaseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.templateBase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTemplateBase([NotNull] JavaccParser.TemplateBaseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.templatePack"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTemplatePack([NotNull] JavaccParser.TemplatePackContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.templatePack"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTemplatePack([NotNull] JavaccParser.TemplatePackContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.classOrInterfaceType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassOrInterfaceType([NotNull] JavaccParser.ClassOrInterfaceTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.classOrInterfaceType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassOrInterfaceType([NotNull] JavaccParser.ClassOrInterfaceTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.typeArguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeArguments([NotNull] JavaccParser.TypeArgumentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.typeArguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeArguments([NotNull] JavaccParser.TypeArgumentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.typeArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeArgument([NotNull] JavaccParser.TypeArgumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.typeArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeArgument([NotNull] JavaccParser.TypeArgumentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.wildcardBounds"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWildcardBounds([NotNull] JavaccParser.WildcardBoundsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.wildcardBounds"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWildcardBounds([NotNull] JavaccParser.WildcardBoundsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.primitiveType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimitiveType([NotNull] JavaccParser.PrimitiveTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.primitiveType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimitiveType([NotNull] JavaccParser.PrimitiveTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.resultType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterResultType([NotNull] JavaccParser.ResultTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.resultType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitResultType([NotNull] JavaccParser.ResultTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterName([NotNull] JavaccParser.NameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitName([NotNull] JavaccParser.NameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.nameList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNameList([NotNull] JavaccParser.NameListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.nameList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNameList([NotNull] JavaccParser.NameListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] JavaccParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] JavaccParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.assignmentOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentOperator([NotNull] JavaccParser.AssignmentOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.assignmentOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentOperator([NotNull] JavaccParser.AssignmentOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.conditionalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditionalExpression([NotNull] JavaccParser.ConditionalExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.conditionalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditionalExpression([NotNull] JavaccParser.ConditionalExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.conditionalOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditionalOrExpression([NotNull] JavaccParser.ConditionalOrExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.conditionalOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditionalOrExpression([NotNull] JavaccParser.ConditionalOrExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.conditionalAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditionalAndExpression([NotNull] JavaccParser.ConditionalAndExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.conditionalAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditionalAndExpression([NotNull] JavaccParser.ConditionalAndExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.inclusiveOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInclusiveOrExpression([NotNull] JavaccParser.InclusiveOrExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.inclusiveOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInclusiveOrExpression([NotNull] JavaccParser.InclusiveOrExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.exclusiveOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExclusiveOrExpression([NotNull] JavaccParser.ExclusiveOrExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.exclusiveOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExclusiveOrExpression([NotNull] JavaccParser.ExclusiveOrExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.andExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAndExpression([NotNull] JavaccParser.AndExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.andExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAndExpression([NotNull] JavaccParser.AndExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.equalityExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEqualityExpression([NotNull] JavaccParser.EqualityExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.equalityExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEqualityExpression([NotNull] JavaccParser.EqualityExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.instanceOfExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstanceOfExpression([NotNull] JavaccParser.InstanceOfExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.instanceOfExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstanceOfExpression([NotNull] JavaccParser.InstanceOfExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelationalExpression([NotNull] JavaccParser.RelationalExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelationalExpression([NotNull] JavaccParser.RelationalExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.shiftExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShiftExpression([NotNull] JavaccParser.ShiftExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.shiftExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShiftExpression([NotNull] JavaccParser.ShiftExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdditiveExpression([NotNull] JavaccParser.AdditiveExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdditiveExpression([NotNull] JavaccParser.AdditiveExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplicativeExpression([NotNull] JavaccParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplicativeExpression([NotNull] JavaccParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryExpression([NotNull] JavaccParser.UnaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryExpression([NotNull] JavaccParser.UnaryExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.preIncrementExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPreIncrementExpression([NotNull] JavaccParser.PreIncrementExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.preIncrementExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPreIncrementExpression([NotNull] JavaccParser.PreIncrementExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.preDecrementExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPreDecrementExpression([NotNull] JavaccParser.PreDecrementExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.preDecrementExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPreDecrementExpression([NotNull] JavaccParser.PreDecrementExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.unaryExpressionNotPlusMinus"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryExpressionNotPlusMinus([NotNull] JavaccParser.UnaryExpressionNotPlusMinusContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.unaryExpressionNotPlusMinus"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryExpressionNotPlusMinus([NotNull] JavaccParser.UnaryExpressionNotPlusMinusContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.castLookahead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCastLookahead([NotNull] JavaccParser.CastLookaheadContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.castLookahead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCastLookahead([NotNull] JavaccParser.CastLookaheadContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.postfixExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPostfixExpression([NotNull] JavaccParser.PostfixExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.postfixExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPostfixExpression([NotNull] JavaccParser.PostfixExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.castExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCastExpression([NotNull] JavaccParser.CastExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.castExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCastExpression([NotNull] JavaccParser.CastExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimaryExpression([NotNull] JavaccParser.PrimaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimaryExpression([NotNull] JavaccParser.PrimaryExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.memberSelector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemberSelector([NotNull] JavaccParser.MemberSelectorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.memberSelector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemberSelector([NotNull] JavaccParser.MemberSelectorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.primaryPrefix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimaryPrefix([NotNull] JavaccParser.PrimaryPrefixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.primaryPrefix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimaryPrefix([NotNull] JavaccParser.PrimaryPrefixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.primarySuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimarySuffix([NotNull] JavaccParser.PrimarySuffixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.primarySuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimarySuffix([NotNull] JavaccParser.PrimarySuffixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral([NotNull] JavaccParser.LiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral([NotNull] JavaccParser.LiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.integerLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntegerLiteral([NotNull] JavaccParser.IntegerLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.integerLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntegerLiteral([NotNull] JavaccParser.IntegerLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.booleanLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBooleanLiteral([NotNull] JavaccParser.BooleanLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.booleanLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBooleanLiteral([NotNull] JavaccParser.BooleanLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.stringLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringLiteral([NotNull] JavaccParser.StringLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.stringLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringLiteral([NotNull] JavaccParser.StringLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.nullLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNullLiteral([NotNull] JavaccParser.NullLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.nullLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNullLiteral([NotNull] JavaccParser.NullLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArguments([NotNull] JavaccParser.ArgumentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArguments([NotNull] JavaccParser.ArgumentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgumentList([NotNull] JavaccParser.ArgumentListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgumentList([NotNull] JavaccParser.ArgumentListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.allocationExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAllocationExpression([NotNull] JavaccParser.AllocationExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.allocationExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAllocationExpression([NotNull] JavaccParser.AllocationExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.arrayDimsAndInits"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayDimsAndInits([NotNull] JavaccParser.ArrayDimsAndInitsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.arrayDimsAndInits"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayDimsAndInits([NotNull] JavaccParser.ArrayDimsAndInitsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] JavaccParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] JavaccParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.assertStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssertStatement([NotNull] JavaccParser.AssertStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.assertStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssertStatement([NotNull] JavaccParser.AssertStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.labeledStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabeledStatement([NotNull] JavaccParser.LabeledStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.labeledStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabeledStatement([NotNull] JavaccParser.LabeledStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] JavaccParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] JavaccParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.blockStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlockStatement([NotNull] JavaccParser.BlockStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.blockStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlockStatement([NotNull] JavaccParser.BlockStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.localVariableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocalVariableDeclaration([NotNull] JavaccParser.LocalVariableDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.localVariableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocalVariableDeclaration([NotNull] JavaccParser.LocalVariableDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.emptyStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmptyStatement([NotNull] JavaccParser.EmptyStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.emptyStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmptyStatement([NotNull] JavaccParser.EmptyStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.statementExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatementExpression([NotNull] JavaccParser.StatementExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.statementExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatementExpression([NotNull] JavaccParser.StatementExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.switchStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchStatement([NotNull] JavaccParser.SwitchStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.switchStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchStatement([NotNull] JavaccParser.SwitchStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.switchLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchLabel([NotNull] JavaccParser.SwitchLabelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.switchLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchLabel([NotNull] JavaccParser.SwitchLabelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStatement([NotNull] JavaccParser.IfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStatement([NotNull] JavaccParser.IfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileStatement([NotNull] JavaccParser.WhileStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileStatement([NotNull] JavaccParser.WhileStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.doStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDoStatement([NotNull] JavaccParser.DoStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.doStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDoStatement([NotNull] JavaccParser.DoStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForStatement([NotNull] JavaccParser.ForStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForStatement([NotNull] JavaccParser.ForStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.forInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForInit([NotNull] JavaccParser.ForInitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.forInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForInit([NotNull] JavaccParser.ForInitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.statementExpressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatementExpressionList([NotNull] JavaccParser.StatementExpressionListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.statementExpressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatementExpressionList([NotNull] JavaccParser.StatementExpressionListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.forUpdate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForUpdate([NotNull] JavaccParser.ForUpdateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.forUpdate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForUpdate([NotNull] JavaccParser.ForUpdateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.breakStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBreakStatement([NotNull] JavaccParser.BreakStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.breakStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBreakStatement([NotNull] JavaccParser.BreakStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.continueStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContinueStatement([NotNull] JavaccParser.ContinueStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.continueStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContinueStatement([NotNull] JavaccParser.ContinueStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStatement([NotNull] JavaccParser.ReturnStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStatement([NotNull] JavaccParser.ReturnStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.throwStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterThrowStatement([NotNull] JavaccParser.ThrowStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.throwStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitThrowStatement([NotNull] JavaccParser.ThrowStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.synchronizedStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSynchronizedStatement([NotNull] JavaccParser.SynchronizedStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.synchronizedStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSynchronizedStatement([NotNull] JavaccParser.SynchronizedStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.resourceDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterResourceDeclaration([NotNull] JavaccParser.ResourceDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.resourceDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitResourceDeclaration([NotNull] JavaccParser.ResourceDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.catchParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCatchParameter([NotNull] JavaccParser.CatchParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.catchParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCatchParameter([NotNull] JavaccParser.CatchParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.tryStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTryStatement([NotNull] JavaccParser.TryStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.tryStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTryStatement([NotNull] JavaccParser.TryStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnnotation([NotNull] JavaccParser.AnnotationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnnotation([NotNull] JavaccParser.AnnotationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.normalAnnotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNormalAnnotation([NotNull] JavaccParser.NormalAnnotationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.normalAnnotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNormalAnnotation([NotNull] JavaccParser.NormalAnnotationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.markerAnnotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMarkerAnnotation([NotNull] JavaccParser.MarkerAnnotationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.markerAnnotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMarkerAnnotation([NotNull] JavaccParser.MarkerAnnotationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.singleMemberAnnotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSingleMemberAnnotation([NotNull] JavaccParser.SingleMemberAnnotationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.singleMemberAnnotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSingleMemberAnnotation([NotNull] JavaccParser.SingleMemberAnnotationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.memberValuePairs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemberValuePairs([NotNull] JavaccParser.MemberValuePairsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.memberValuePairs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemberValuePairs([NotNull] JavaccParser.MemberValuePairsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.memberValuePair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemberValuePair([NotNull] JavaccParser.MemberValuePairContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.memberValuePair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemberValuePair([NotNull] JavaccParser.MemberValuePairContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.memberValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemberValue([NotNull] JavaccParser.MemberValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.memberValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemberValue([NotNull] JavaccParser.MemberValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.memberValueArrayInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemberValueArrayInitializer([NotNull] JavaccParser.MemberValueArrayInitializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.memberValueArrayInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemberValueArrayInitializer([NotNull] JavaccParser.MemberValueArrayInitializerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.annotationTypeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnnotationTypeDeclaration([NotNull] JavaccParser.AnnotationTypeDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.annotationTypeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnnotationTypeDeclaration([NotNull] JavaccParser.AnnotationTypeDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.annotationTypeBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnnotationTypeBody([NotNull] JavaccParser.AnnotationTypeBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.annotationTypeBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnnotationTypeBody([NotNull] JavaccParser.AnnotationTypeBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.annotationTypeMemberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnnotationTypeMemberDeclaration([NotNull] JavaccParser.AnnotationTypeMemberDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.annotationTypeMemberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnnotationTypeMemberDeclaration([NotNull] JavaccParser.AnnotationTypeMemberDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaccParser.defaultValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefaultValue([NotNull] JavaccParser.DefaultValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaccParser.defaultValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefaultValue([NotNull] JavaccParser.DefaultValueContext context);
}
