//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from xtext.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="xtextParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IxtextVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStart([NotNull] xtextParser.StartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.grammarID"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGrammarID([NotNull] xtextParser.GrammarIDContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.abstractRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAbstractRule([NotNull] xtextParser.AbstractRuleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.abstractMetamodelDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAbstractMetamodelDeclaration([NotNull] xtextParser.AbstractMetamodelDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.generatedMetamodel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneratedMetamodel([NotNull] xtextParser.GeneratedMetamodelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.referencedMetamodel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReferencedMetamodel([NotNull] xtextParser.ReferencedMetamodelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotation([NotNull] xtextParser.AnnotationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.parserRule_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParserRule_([NotNull] xtextParser.ParserRule_Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.ruleNameAndParams"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRuleNameAndParams([NotNull] xtextParser.RuleNameAndParamsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter([NotNull] xtextParser.ParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.typeRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeRef([NotNull] xtextParser.TypeRefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.alternatives"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlternatives([NotNull] xtextParser.AlternativesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.conditionalBranch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditionalBranch([NotNull] xtextParser.ConditionalBranchContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.unorderedGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnorderedGroup([NotNull] xtextParser.UnorderedGroupContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroup([NotNull] xtextParser.GroupContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.abstractToken"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAbstractToken([NotNull] xtextParser.AbstractTokenContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.abstractTokenWithCardinality"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAbstractTokenWithCardinality([NotNull] xtextParser.AbstractTokenWithCardinalityContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAction([NotNull] xtextParser.ActionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.abstractTerminal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAbstractTerminal([NotNull] xtextParser.AbstractTerminalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKeyword([NotNull] xtextParser.KeywordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.ruleCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRuleCall([NotNull] xtextParser.RuleCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.namedArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamedArgument([NotNull] xtextParser.NamedArgumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.literalCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteralCondition([NotNull] xtextParser.LiteralConditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.disjunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDisjunction([NotNull] xtextParser.DisjunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.conjunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConjunction([NotNull] xtextParser.ConjunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.negation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNegation([NotNull] xtextParser.NegationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtom([NotNull] xtextParser.AtomContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.parenthesizedCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenthesizedCondition([NotNull] xtextParser.ParenthesizedConditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.parameterReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterReference([NotNull] xtextParser.ParameterReferenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.terminalRuleCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerminalRuleCall([NotNull] xtextParser.TerminalRuleCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.ruleID"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRuleID([NotNull] xtextParser.RuleIDContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.validID"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValidID([NotNull] xtextParser.ValidIDContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.predicatedKeyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPredicatedKeyword([NotNull] xtextParser.PredicatedKeywordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.predicatedRuleCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPredicatedRuleCall([NotNull] xtextParser.PredicatedRuleCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] xtextParser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.assignableTerminal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignableTerminal([NotNull] xtextParser.AssignableTerminalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.parenthesizedAssignableElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenthesizedAssignableElement([NotNull] xtextParser.ParenthesizedAssignableElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.assignableAlternatives"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignableAlternatives([NotNull] xtextParser.AssignableAlternativesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.crossReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCrossReference([NotNull] xtextParser.CrossReferenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.crossReferenceableTerminal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCrossReferenceableTerminal([NotNull] xtextParser.CrossReferenceableTerminalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.parenthesizedElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenthesizedElement([NotNull] xtextParser.ParenthesizedElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.predicatedGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPredicatedGroup([NotNull] xtextParser.PredicatedGroupContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.terminalRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerminalRule([NotNull] xtextParser.TerminalRuleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.terminalAlternatives"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerminalAlternatives([NotNull] xtextParser.TerminalAlternativesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.terminalGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerminalGroup([NotNull] xtextParser.TerminalGroupContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.terminalToken"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerminalToken([NotNull] xtextParser.TerminalTokenContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.terminalTokenElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerminalTokenElement([NotNull] xtextParser.TerminalTokenElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.parenthesizedTerminalElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenthesizedTerminalElement([NotNull] xtextParser.ParenthesizedTerminalElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.abstractNegatedToken"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAbstractNegatedToken([NotNull] xtextParser.AbstractNegatedTokenContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.negatedToken"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNegatedToken([NotNull] xtextParser.NegatedTokenContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.untilToken"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUntilToken([NotNull] xtextParser.UntilTokenContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.wildcard"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWildcard([NotNull] xtextParser.WildcardContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.eOF"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEOF([NotNull] xtextParser.EOFContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.characterRange"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCharacterRange([NotNull] xtextParser.CharacterRangeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.enumRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumRule([NotNull] xtextParser.EnumRuleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.enumLiterals"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumLiterals([NotNull] xtextParser.EnumLiteralsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="xtextParser.enumLiteralDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumLiteralDeclaration([NotNull] xtextParser.EnumLiteralDeclarationContext context);
}
