using System;

/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the  "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * $Id: ElemText.java 468643 2006-10-28 06:56:03Z minchau $
 */
namespace org.apache.xalan.templates
{

	using XSLTErrorResources = org.apache.xalan.res.XSLTErrorResources;

	/// <summary>
	/// Implement xsl:template.
	/// This primarily acts as a marker on the element
	/// stack to signal that whitespace should be preserved.
	/// <pre>
	/// <!ELEMENT xsl:text (#PCDATA)>
	/// <!ATTLIST xsl:text
	///   disable-output-escaping (yes|no) "no"
	/// >
	/// </pre> </summary>
	/// <seealso cref= <a href="http://www.w3.org/TR/xslt#section-Creating-Text">section-Creating-Text in XSLT Specification</a>
	/// @xsl.usage advanced </seealso>
	[Serializable]
	public class ElemText : ElemTemplateElement
	{
		internal new const long serialVersionUID = 1383140876182316711L;

	  /// <summary>
	  /// Tells if this element should disable escaping.
	  /// @serial
	  /// </summary>
	  private bool m_disableOutputEscaping = false;

	  /// <summary>
	  /// Set the "disable-output-escaping" attribute.
	  /// Normally, the xml output method escapes & and < (and
	  /// possibly other characters) when outputting text nodes.
	  /// This ensures that the output is well-formed XML. However,
	  /// it is sometimes convenient to be able to produce output
	  /// that is almost, but not quite well-formed XML; for
	  /// example, the output may include ill-formed sections
	  /// which are intended to be transformed into well-formed
	  /// XML by a subsequent non-XML aware process. For this reason,
	  /// XSLT provides a mechanism for disabling output escaping.
	  /// An xsl:value-of or xsl:text element may have a
	  /// disable-output-escaping attribute; the allowed values
	  /// are yes or no; the default is no; if the value is yes,
	  /// then a text node generated by instantiating the xsl:value-of
	  /// or xsl:text element should be output without any escaping. </summary>
	  /// <seealso cref= <a href="http://www.w3.org/TR/xslt#disable-output-escaping">disable-output-escaping in XSLT Specification</a>
	  /// </seealso>
	  /// <param name="v"> Boolean flag indicating whether this element should disable escaping </param>
	  public virtual bool DisableOutputEscaping
	  {
		  set
		  {
			m_disableOutputEscaping = value;
		  }
		  get
		  {
			return m_disableOutputEscaping;
		  }
	  }


	  /// <summary>
	  /// Get an integer representation of the element type.
	  /// </summary>
	  /// <returns> An integer representation of the element, defined in the
	  ///     Constants class. </returns>
	  /// <seealso cref= org.apache.xalan.templates.Constants </seealso>
	  public override int XSLToken
	  {
		  get
		  {
			return Constants.ELEMNAME_TEXT;
		  }
	  }

	  /// <summary>
	  /// Return the node name.
	  /// </summary>
	  /// <returns> The element's name </returns>
	  public override string NodeName
	  {
		  get
		  {
			return Constants.ELEMNAME_TEXT_STRING;
		  }
	  }

	  /// <summary>
	  /// Add a child to the child list.
	  /// </summary>
	  /// <param name="newChild"> Child to add to children list
	  /// </param>
	  /// <returns> Child added to children list
	  /// </returns>
	  /// <exception cref="DOMException"> </exception>
	  public override ElemTemplateElement appendChild(ElemTemplateElement newChild)
	  {

		int type = ((ElemTemplateElement) newChild).XSLToken;

		switch (type)
		{
		case Constants.ELEMNAME_TEXTLITERALRESULT :
		  break;
		default :
		  error(XSLTErrorResources.ER_CANNOT_ADD, new object[]{newChild.NodeName, this.NodeName}); //"Can not add " +((ElemTemplateElement)newChild).m_elemName +

		//" to " + this.m_elemName);
	  break;
		}

		return base.appendChild(newChild);
	  }
	}

}