//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from W3CebnfParser.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IW3CebnfParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class W3CebnfParserBaseListener : IW3CebnfParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="W3CebnfParser.grammar_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGrammar_([NotNull] W3CebnfParser.Grammar_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="W3CebnfParser.grammar_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGrammar_([NotNull] W3CebnfParser.Grammar_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="W3CebnfParser.production"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProduction([NotNull] W3CebnfParser.ProductionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="W3CebnfParser.production"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProduction([NotNull] W3CebnfParser.ProductionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="W3CebnfParser.choice"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterChoice([NotNull] W3CebnfParser.ChoiceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="W3CebnfParser.choice"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitChoice([NotNull] W3CebnfParser.ChoiceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="W3CebnfParser.sequence_or_difference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSequence_or_difference([NotNull] W3CebnfParser.Sequence_or_differenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="W3CebnfParser.sequence_or_difference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSequence_or_difference([NotNull] W3CebnfParser.Sequence_or_differenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="W3CebnfParser.item"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterItem([NotNull] W3CebnfParser.ItemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="W3CebnfParser.item"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitItem([NotNull] W3CebnfParser.ItemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="W3CebnfParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimary([NotNull] W3CebnfParser.PrimaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="W3CebnfParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimary([NotNull] W3CebnfParser.PrimaryContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
