$x instance of jnode(),
$x instance of jnode(*),
$x instance of jnode(()),
$x instance of jnode(foo),
$x instance of jnode('key'),
$x instance of jnode(0),
$x instance of jnode(-1),
$x instance of jnode(#foo),
$x instance of jnode(true())
