//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from pegen_v3_10Parser.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="Ipegen_v3_10ParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class pegen_v3_10ParserBaseListener : Ipegen_v3_10ParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="pegen_v3_10Parser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStart([NotNull] pegen_v3_10Parser.StartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pegen_v3_10Parser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStart([NotNull] pegen_v3_10Parser.StartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pegen_v3_10Parser.grammar_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGrammar_([NotNull] pegen_v3_10Parser.Grammar_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pegen_v3_10Parser.grammar_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGrammar_([NotNull] pegen_v3_10Parser.Grammar_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pegen_v3_10Parser.metas"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMetas([NotNull] pegen_v3_10Parser.MetasContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pegen_v3_10Parser.metas"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMetas([NotNull] pegen_v3_10Parser.MetasContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pegen_v3_10Parser.meta"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMeta([NotNull] pegen_v3_10Parser.MetaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pegen_v3_10Parser.meta"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMeta([NotNull] pegen_v3_10Parser.MetaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pegen_v3_10Parser.rules"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRules([NotNull] pegen_v3_10Parser.RulesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pegen_v3_10Parser.rules"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRules([NotNull] pegen_v3_10Parser.RulesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pegen_v3_10Parser.rule_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_([NotNull] pegen_v3_10Parser.Rule_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pegen_v3_10Parser.rule_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_([NotNull] pegen_v3_10Parser.Rule_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pegen_v3_10Parser.rulename"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRulename([NotNull] pegen_v3_10Parser.RulenameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pegen_v3_10Parser.rulename"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRulename([NotNull] pegen_v3_10Parser.RulenameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pegen_v3_10Parser.attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttribute([NotNull] pegen_v3_10Parser.AttributeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pegen_v3_10Parser.attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttribute([NotNull] pegen_v3_10Parser.AttributeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pegen_v3_10Parser.memoflag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMemoflag([NotNull] pegen_v3_10Parser.MemoflagContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pegen_v3_10Parser.memoflag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMemoflag([NotNull] pegen_v3_10Parser.MemoflagContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pegen_v3_10Parser.alts"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAlts([NotNull] pegen_v3_10Parser.AltsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pegen_v3_10Parser.alts"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAlts([NotNull] pegen_v3_10Parser.AltsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pegen_v3_10Parser.more_alts"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMore_alts([NotNull] pegen_v3_10Parser.More_altsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pegen_v3_10Parser.more_alts"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMore_alts([NotNull] pegen_v3_10Parser.More_altsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pegen_v3_10Parser.alt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAlt([NotNull] pegen_v3_10Parser.AltContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pegen_v3_10Parser.alt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAlt([NotNull] pegen_v3_10Parser.AltContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pegen_v3_10Parser.items"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterItems([NotNull] pegen_v3_10Parser.ItemsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pegen_v3_10Parser.items"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitItems([NotNull] pegen_v3_10Parser.ItemsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pegen_v3_10Parser.named_item"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamed_item([NotNull] pegen_v3_10Parser.Named_itemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pegen_v3_10Parser.named_item"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamed_item([NotNull] pegen_v3_10Parser.Named_itemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pegen_v3_10Parser.attribute_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttribute_name([NotNull] pegen_v3_10Parser.Attribute_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pegen_v3_10Parser.attribute_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttribute_name([NotNull] pegen_v3_10Parser.Attribute_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pegen_v3_10Parser.forced_atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForced_atom([NotNull] pegen_v3_10Parser.Forced_atomContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pegen_v3_10Parser.forced_atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForced_atom([NotNull] pegen_v3_10Parser.Forced_atomContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pegen_v3_10Parser.lookahead"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLookahead([NotNull] pegen_v3_10Parser.LookaheadContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pegen_v3_10Parser.lookahead"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLookahead([NotNull] pegen_v3_10Parser.LookaheadContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pegen_v3_10Parser.item"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterItem([NotNull] pegen_v3_10Parser.ItemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pegen_v3_10Parser.item"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitItem([NotNull] pegen_v3_10Parser.ItemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pegen_v3_10Parser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtom([NotNull] pegen_v3_10Parser.AtomContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pegen_v3_10Parser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtom([NotNull] pegen_v3_10Parser.AtomContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pegen_v3_10Parser.action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAction([NotNull] pegen_v3_10Parser.ActionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pegen_v3_10Parser.action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAction([NotNull] pegen_v3_10Parser.ActionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pegen_v3_10Parser.name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterName([NotNull] pegen_v3_10Parser.NameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pegen_v3_10Parser.name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitName([NotNull] pegen_v3_10Parser.NameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pegen_v3_10Parser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString([NotNull] pegen_v3_10Parser.StringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pegen_v3_10Parser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString([NotNull] pegen_v3_10Parser.StringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pegen_v3_10Parser.newline"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNewline([NotNull] pegen_v3_10Parser.NewlineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pegen_v3_10Parser.newline"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNewline([NotNull] pegen_v3_10Parser.NewlineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pegen_v3_10Parser.indent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndent([NotNull] pegen_v3_10Parser.IndentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pegen_v3_10Parser.indent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndent([NotNull] pegen_v3_10Parser.IndentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pegen_v3_10Parser.dedent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDedent([NotNull] pegen_v3_10Parser.DedentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pegen_v3_10Parser.dedent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDedent([NotNull] pegen_v3_10Parser.DedentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pegen_v3_10Parser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber([NotNull] pegen_v3_10Parser.NumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pegen_v3_10Parser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber([NotNull] pegen_v3_10Parser.NumberContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
